config-version: 2

name: 'zendesk_source'
version: '0.3.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  zendesk_source:
    materialized: view
    tmp:
      enabled: false

vars:
  zendesk_source:
    group:                "{{ source('zendesk', 'group') }}"
    brand:                "{{ source('zendesk', 'brand') }}"
    domain_name:          "{{ source('zendesk', 'domain_name') }}"
    organization_tag:     "{{ source('zendesk', 'organization_tag') }}"
    organization:         "{{ source('zendesk', 'organization') }}"
    schedule:             "{{ source('zendesk', 'schedule') }}"
    satisfaction_rating:  "{{ source('zendesk', 'satisfaction_rating') }}"
    ticket:               "{{ source('zendesk', 'ticket') }}"
    ticket_form_history:  "{{ source('zendesk', 'ticket_form_history') }}"
    ticket_comment:       "{{ source('zendesk', 'ticket_comment') }}"
    ticket_field_history: "{{ source('zendesk', 'ticket_field_history') }}"
    ticket_schedule:      "{{ source('zendesk', 'ticket_schedule') }}"
    ticket_tag:           "{{ source('zendesk', 'ticket_tag') }}"
    user_tag:             "{{ source('zendesk', 'user_tag') }}"
    user:                 "{{ source('zendesk', 'user') }}"

    using_schedules:            True
    using_domain_names:         True
    using_user_tags:            True
    using_ticket_form_history:  True
    using_organization_tags:    True
    using_satisfaction_ratings: True
