config-version: 2

name: 'zendesk_source_integration_tests'
version: '0.3.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]
profile: 'integration_tests'

vars:
  zendesk_schema: zendesk_source_integration_tests
  zendesk_source:
    using_schedules:            True
    using_domain_names:         True
    using_user_tags:            True
    using_ticket_form_history:  True
    using_organization_tags:    True

clean-targets:
    - target
    - dbt_modules
