config-version: 2

name: 'zendesk_source_integration_tests'
version: '0.3.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]
profile: 'integration_tests'

vars:
  zendesk_database: raw
  zendesk_schema: raw_fivetran_zendesk
  zendesk_source:
    using_schedules:            true
    using_domain_names:         true
    using_user_tags:            false
    using_ticket_form_history:  true
    using_organization_tags:    false

clean-targets:
    - target
    - dbt_modules
