
# HEY! This file is used in the Github integrations tests with CircleCI.
# You should __NEVER__ check credentials into version control. Thanks for reading :)

config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: "{{ env_var('CI_SNOWFLAKE_DBT_ACCOUNT') }}"
      user: "{{ env_var('CI_SNOWFLAKE_DBT_USER') }}"
      password: "{{ env_var('CI_SNOWFLAKE_DBT_PASS') }}"
      role: "{{ env_var('CI_SNOWFLAKE_DBT_ROLE') }}"
      database: "{{ env_var('CI_SNOWFLAKE_DBT_DATABASE') }}"
      warehouse: "{{ env_var('CI_SNOWFLAKE_DBT_WAREHOUSE') }}"
      schema: "{{ env_var('CI_SNOWFLAKE_DBT_SCHEMA') }}"
      threads: 8
